// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestiaappdemo/swap/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreatePair struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	Token0 string `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty" yaml:"token0"`
	Token1 string `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty" yaml:"token1"`
}

func (m *MsgCreatePair) Reset()         { *m = MsgCreatePair{} }
func (m *MsgCreatePair) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePair) ProtoMessage()    {}
func (*MsgCreatePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec9fc14dce5f9df, []int{0}
}
func (m *MsgCreatePair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePair.Merge(m, src)
}
func (m *MsgCreatePair) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePair) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePair.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePair proto.InternalMessageInfo

func (m *MsgCreatePair) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCreatePair) GetToken0() string {
	if m != nil {
		return m.Token0
	}
	return ""
}

func (m *MsgCreatePair) GetToken1() string {
	if m != nil {
		return m.Token1
	}
	return ""
}

type MsgCreateaPairResponse struct {
	NewLpToken string `protobuf:"bytes,1,opt,name=new_lp_token,json=newLpToken,proto3" json:"new_lp_token,omitempty" yaml:"new_lp_token"`
}

func (m *MsgCreateaPairResponse) Reset()         { *m = MsgCreateaPairResponse{} }
func (m *MsgCreateaPairResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateaPairResponse) ProtoMessage()    {}
func (*MsgCreateaPairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec9fc14dce5f9df, []int{1}
}
func (m *MsgCreateaPairResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateaPairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateaPairResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateaPairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateaPairResponse.Merge(m, src)
}
func (m *MsgCreateaPairResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateaPairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateaPairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateaPairResponse proto.InternalMessageInfo

func (m *MsgCreateaPairResponse) GetNewLpToken() string {
	if m != nil {
		return m.NewLpToken
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCreatePair)(nil), "celestiaappdemo.swap.v1beta1.MsgCreatePair")
	proto.RegisterType((*MsgCreateaPairResponse)(nil), "celestiaappdemo.swap.v1beta1.MsgCreateaPairResponse")
}

func init() {
	proto.RegisterFile("celestiaappdemo/swap/v1beta1/tx.proto", fileDescriptor_9ec9fc14dce5f9df)
}

var fileDescriptor_9ec9fc14dce5f9df = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0x33, 0x31,
	0x14, 0x85, 0x9b, 0xbf, 0x50, 0xf8, 0x83, 0x5d, 0x38, 0x8a, 0x96, 0x22, 0xa9, 0x04, 0x04, 0x45,
	0x3a, 0xe3, 0xa8, 0x0b, 0x75, 0x59, 0xb7, 0x16, 0x64, 0x74, 0xe5, 0xa6, 0xa4, 0xed, 0x65, 0x28,
	0x6d, 0x93, 0x30, 0x09, 0x9d, 0xf6, 0x2d, 0xfa, 0x58, 0x2e, 0xbb, 0x74, 0x55, 0x64, 0xe6, 0x0d,
	0xfa, 0x04, 0x92, 0xc9, 0x74, 0x68, 0xab, 0x88, 0xbb, 0xdc, 0x7b, 0xbe, 0x1c, 0x4e, 0x6e, 0x2e,
	0x3e, 0xeb, 0xc1, 0x08, 0x94, 0x1e, 0x30, 0x26, 0x65, 0x1f, 0xc6, 0xc2, 0x53, 0x31, 0x93, 0xde,
	0xc4, 0xef, 0x82, 0x66, 0xbe, 0xa7, 0xa7, 0xae, 0x8c, 0x84, 0x16, 0xce, 0xc9, 0x0e, 0xe6, 0x1a,
	0xcc, 0xcd, 0xb1, 0xfa, 0x61, 0x28, 0x42, 0x91, 0x81, 0x9e, 0x39, 0xd9, 0x3b, 0x75, 0xd2, 0x13,
	0x6a, 0x2c, 0x94, 0xd7, 0x65, 0x0a, 0x0a, 0xc7, 0x9e, 0x18, 0xf0, 0x6f, 0x3a, 0x1f, 0x16, 0xba,
	0x29, 0xac, 0x4e, 0xe7, 0x08, 0x57, 0xdb, 0x2a, 0x7c, 0x8c, 0x80, 0x69, 0x78, 0x66, 0x83, 0xc8,
	0xb9, 0xc0, 0x15, 0x05, 0xbc, 0x0f, 0x51, 0x0d, 0x9d, 0xa2, 0xf3, 0xff, 0xad, 0xfd, 0xd5, 0xb2,
	0x51, 0x9d, 0xb1, 0xf1, 0xe8, 0x81, 0xda, 0x3e, 0x0d, 0x72, 0xc0, 0xa0, 0x5a, 0x0c, 0x81, 0x5f,
	0xd5, 0xfe, 0xed, 0xa2, 0xb6, 0x4f, 0x83, 0x1c, 0x28, 0x50, 0xbf, 0x56, 0xfe, 0x11, 0xf5, 0xd7,
	0xa8, 0x4f, 0x5f, 0xf0, 0x51, 0x91, 0x88, 0x99, 0x48, 0x01, 0x28, 0x29, 0xb8, 0x02, 0xe7, 0x1e,
	0xef, 0x71, 0x88, 0x3b, 0x23, 0xd9, 0xc9, 0xd0, 0x3c, 0xe0, 0xf1, 0x6a, 0xd9, 0x38, 0xb0, 0x56,
	0x9b, 0x2a, 0x0d, 0x30, 0x87, 0xf8, 0x49, 0xbe, 0x9a, 0xe2, 0x7a, 0x82, 0xcb, 0x6d, 0x15, 0x3a,
	0x02, 0xe3, 0x8d, 0xa7, 0x5e, 0xba, 0xbf, 0x4d, 0xdc, 0xdd, 0x9a, 0x4b, 0xfd, 0xf6, 0x8f, 0xf0,
	0x56, 0xe4, 0xd6, 0xdd, 0x7b, 0x42, 0xd0, 0x22, 0x21, 0xe8, 0x33, 0x21, 0x68, 0x9e, 0x92, 0xd2,
	0x22, 0x25, 0xa5, 0x8f, 0x94, 0x94, 0xde, 0xc8, 0xda, 0xae, 0xc9, 0xa4, 0x6c, 0x66, 0x6b, 0x31,
	0xb5, 0x8b, 0xa1, 0x67, 0x12, 0x54, 0xb7, 0x92, 0x7d, 0xd0, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x20, 0xcf, 0xc6, 0x41, 0x3d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreatePair(ctx context.Context, in *MsgCreatePair, opts ...grpc.CallOption) (*MsgCreateaPairResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePair(ctx context.Context, in *MsgCreatePair, opts ...grpc.CallOption) (*MsgCreateaPairResponse, error) {
	out := new(MsgCreateaPairResponse)
	err := c.cc.Invoke(ctx, "/celestiaappdemo.swap.v1beta1.Msg/CreatePair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreatePair(context.Context, *MsgCreatePair) (*MsgCreateaPairResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePair(ctx context.Context, req *MsgCreatePair) (*MsgCreateaPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePair not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestiaappdemo.swap.v1beta1.Msg/CreatePair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePair(ctx, req.(*MsgCreatePair))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestiaappdemo.swap.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePair",
			Handler:    _Msg_CreatePair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestiaappdemo/swap/v1beta1/tx.proto",
}

func (m *MsgCreatePair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token1) > 0 {
		i -= len(m.Token1)
		copy(dAtA[i:], m.Token1)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Token1)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Token0) > 0 {
		i -= len(m.Token0)
		copy(dAtA[i:], m.Token0)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Token0)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateaPairResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateaPairResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateaPairResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewLpToken) > 0 {
		i -= len(m.NewLpToken)
		copy(dAtA[i:], m.NewLpToken)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewLpToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Token0)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Token1)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateaPairResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NewLpToken)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token0 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateaPairResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateaPairResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateaPairResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLpToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewLpToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
